version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: submitter_local

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:password@db/submitter_local"
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: "false"
      RAILS_LOG_TO_STDOUT: "true"
      AUTH_BASIC_PASSWORD: "hello"
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - $PWD:/app

